# Generated by Django 5.1.2 on 2025-03-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('files', models.FileField(blank=True, null=True, upload_to='files_upload/')),
                ('addDate', models.DateField()),
            ],
        ),
    ]
