# Generated by Django 5.1.2 on 2025-03-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
