# Generated by Django 5.1.2 on 2025-03-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploder', '0002_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.FileField(default=None, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='cover/'),
        ),
    ]
